# Generated by Django 3.2.25 on 2024-08-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0002_auto_20240817_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('bio', models.TextField()),
                ('phone_number', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='technicians', to='Technicians_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Technicians',
        ),
    ]
