# Generated by Django 3.2.25 on 2024-08-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0003_auto_20240817_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='technician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='technician_reviews', to='Technicians_app.technician'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='Technicians_app.user'),
        ),
    ]
