# Generated by Django 2.2.4 on 2024-08-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0003_auto_20240821_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='last_name',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
