# Generated by Django 2.2.4 on 2024-08-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0004_auto_20240821_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
