# Generated by Django 3.2.25 on 2024-08-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0004_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='details',
            new_name='message',
        ),
    ]
