# Generated by Django 3.2.25 on 2024-08-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0005_rename_details_contactform_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
