# Generated by Django 2.2.4 on 2024-08-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0006_auto_20240822_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='technicians', to='Technicians_app.User'),
        ),
    ]
