# Generated by Django 2.2.4 on 2024-08-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0006_rename_contactform_contact'),
        ('Technicians_app', '0007_auto_20240822_0051'),
    ]

    operations = [
    ]
