# Generated by Django 3.2.25 on 2024-08-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0008_merge_20240822_1350'),
        ('Technicians_app', '0008_merge_20240822_1650'),
        ('Technicians_app', '0008_merge_20240822_1657'),
    ]

    operations = [
    ]
