# Generated by Django 2.2.4 on 2024-08-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0008_merge_20240822_1350'),
        ('Technicians_app', '0008_merge_20240822_1650'),
        ('Technicians_app', '0008_merge_20240822_1657'),
    ]

    operations = [
    ]
