# Generated by Django 3.2.25 on 2024-08-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0009_merge_20240823_1815'),
        ('Technicians_app', '0009_merge_20240823_2124'),
    ]

    operations = [
    ]
