# Generated by Django 2.2.4 on 2024-08-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0009_merge_20240823_2124'),
        ('Technicians_app', '0009_merge_20240823_1815'),
    ]

    operations = [
    ]
