# Generated by Django 5.1 on 2024-08-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0010_merge_20240824_1303'),
        ('Technicians_app', '0010_merge_20240824_1905'),
    ]

    operations = [
    ]
