# Generated by Django 3.2.25 on 2024-08-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0010_merge_20240824_1303'),
        ('Technicians_app', '0010_merge_20240824_1604'),
        ('Technicians_app', '0010_merge_20240824_1905'),
    ]

    operations = [
    ]
