# Generated by Django 3.2.25 on 2024-08-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0011_merge_20240824_1626'),
        ('Technicians_app', '0011_merge_20240824_2031'),
        ('Technicians_app', '0012_auto_20240825_1959'),
    ]

    operations = [
    ]
