# Generated by Django 5.1 on 2024-08-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians_app', '0013_admin_alter_role_id'),
        ('Technicians_app', '0013_merge_20240825_2038'),
    ]

    operations = [
    ]
